version: '2'

services:
  db:
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./importdb:/docker-entrypoint-initdb.d"
    environment:
      # please adjust these values in the importdb folder as well!!!
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espo
      MYSQL_PASSWORD: secret2
    expose:
      - "3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - "./espocrm-data:/var/www/data"
    ports:
      - "8888:80"
