version: '2'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/var/lib/espocrm/db/data:/var/lib/mysql"
      - "/var/lib/espocrm/db/import:/docker-entrypoint-initdb.d"
    environment:
      # please adjust these values in the importdb folder as well!!!
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - "/var/lib/espocrm/espocrm-data:/var/www/data"
      - "/var/lib/espocrm/espocrm-custom:/var/www/custom"
    environment:
      PROJECT_URL: ${ESPO_PROJECT_URL}
    ports:
      - "8120:80"
    restart: always
